### ISSUE TITLE
RaggedArray third-dimension slice

### ISSUE THREAD

**Issue by justinrporter** [bowman-lab/enspara#164]
It appears not to be possible to calculate slice a stride in the third dimesion of a `RaggedArray`:

```python
a = ra.RaggedArray(np.zeros((100, 2)), lengths=[90, 10])
a[:, :, ::2]
```

gives

```
ValueError                                Traceback (most recent call last)
<ipython-input-37-64bea6dd4686> in <module>()
      1 a = ra.RaggedArray(np.zeros((100, 2)), lengths=[90, 10])
----> 2 a[:, :, ::2]

~/modules/enspara/ra/ra.py in __getitem__(self, iis)
    531         # tuples get index conversion from 2d to 1d
    532         elif isinstance(iis, tuple):
--> 533             first_dimension, second_dimension = iis
    534             # if the first dimension is a slice, converts both sets of indices
    535             if isinstance(first_dimension, slice):

ValueError: too many values to unpack (expected 2)
```

@mizimmer90 is this a bug or expected behavior? It seems very reasonable to want to do this.

**Comment by mizimmer90** [comment]
This is expected behavior. While it is reasonable to want this, the ragged array is currently only supported for 2 dimensions.

**Comment by justinrporter** [comment]
> the ragged array is currently only supported for 2 dimensions

it is not obvious to me why this prevents a null slice from setting all the elements? In numpy, 

```python
a = np.zeros((2, 2, 2))
a[:] = -1
```

gives

```
array([[[-1., -1.],
        [-1., -1.]],

       [[-1., -1.],
        [-1., -1.]]])
```

and the same behavior is present any number of dimensions, from 1 to whatever the maximum is.

**Comment by mizimmer90** [comment]
I think you might have the issue requests mixed up? See https://github.com/bowman-lab/enspara/pull/172

**Comment by justinrporter** [comment]
Word.
