### ISSUE TITLE
Number of frames distributed to centroids

### ISSUE THREAD

**Issue by PeptideSimulator01** [bowman-lab/enspara#194]
Dear all,

enspara was recomended to my by (https://github.com/mdtraj/mdtraj/issues/1544#issuecomment-621988616) and so far, I absolutely enjoy how fast clustering is done! 84 seconds for 175000 frames is insane!

I clustered my trajectories (20 clusters) and got the fs-khybrid-clusters0020-centers.pickle file, which mdjoined afterwards. Then i converted this into a pdb.

My question now is, how do I know which clusters is used the most? So how many frames where assigned to one cluster?

The code I used:
```
/enspara/enspara/apps$ python cluster.py \
>   --trajectories production*.h5 \
>   --topology topology.pdb \
>   --algorithm khybrid \
>   --cluster-number 20 \
>   --atoms '(name N or name C or name CA)' \
>   --distances /home/user/enspara/enspara/apps/fs-khybrid-clusters0020-distances.h5 \
>   --center-features /home/user/enspara/enspara/apps/fs-khybrid-clusters0020-centers.pickle \
>   --assignments /home/user/enspara/enspara/apps/fs-khybrid-clusters0020-assignments.h5

>>> import pickle
>>> import mdtraj as md
>>>
>>> with open('fs-khybrid-clusters0020-centers.pickle', 'rb') as f:
...     ctr_structs = md.join(pickle.load(f))

>>> ctr_structs.save_pdb('test.pdb)

```

Any help is appreciated.

**Comment by justinrporter** [comment]
There are a couple ways to answer your question.

1. The assignments file (load with `enspara.ra.load`) will contain an assignment of every frame to a center, such that the number at position (_t_, _i_) indicates which of the 20 cluster center frame _i_ of trajectory _t_ it was closest to.
2. You could fit an MSM (per the "Fitting" section of the tutorial), which uses the transition probabilities to estimate the equilibrium probability of being in a particular state.

I'll add some detail about this to the tutorial!
