### ISSUE TITLE
Setup.py and documentation question

### ISSUE THREAD

**Issue by matthew-cruz** [bowman-lab/enspara#203]
1. in the installation documentation, shown below, the numpy install has '==' is that a typo?
```
conda install -c conda-forge mdtraj=1.8.0
conda install numpy==1.14
conda install cython
conda install mpi4py -c conda-forge
```

2. when running ```python setup.py install``` I keep getting this error ```--------------------------------------------------------------------------------Error: building enspara requires numpy and cython>=0.19
Try running the command ``pip install numpy cython`` or``conda install numpy cython``.
or see http://docs.scipy.org/doc/numpy/user/install.html andhttp://cython.org/ for more information.Traceback (most recent call last):
  File "setup.py", line 105, in <module>
    include_dirs=[np.get_include()],
NameError: name 'np' is not defined```

despite the fact that if I do ```ipython import numpy as np``` there's no problem. I also tried the conda install etc and all the versions and modules are installed. Am I missing something?

**Comment by justinrporter** [comment]
What about cython?

The relevant part of `setup.py` is:
```
try:
    import numpy as np
    import Cython
    if Cython.__version__ < '0.19':
        raise ImportError
    from Cython.Build import cythonize
except ImportError:
    sys.stderr.write('-' * 80)
    sys.stderr.write('\n'.join([
        'Error: building enspara requires numpy and cython>=0.19',
        'Try running the command ``pip install numpy cython`` or'
        '``conda install numpy cython``.',

        'or see http://docs.scipy.org/doc/numpy/user/install.html and'
        'http://cython.org/ for more information.']))
```

As you can see, if you error out on any of those lines under "try" you'll get that same error.

**Comment by MMLawal** [comment]
Hello, my enspara is failing to execute with the traceback error below, kindly advise.

INFO:numexpr.utils:NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "/Users/monsurat/opt/anaconda3/bin/enspara", line 33, in <module>
    sys.exit(load_entry_point('enspara==0.1.1', 'console_scripts', 'enspara')())
  File "/Users/monsurat/opt/anaconda3/lib/python3.8/site-packages/enspara-0.1.1-py3.8-macosx-10.9-x86_64.egg/enspara/apps/main.py", line 44, in main
    args = identify_app(argv)
  File "/Users/monsurat/opt/anaconda3/lib/python3.8/site-packages/enspara-0.1.1-py3.8-macosx-10.9-x86_64.egg/enspara/apps/main.py", line 23, in identify_app
    while h in argv and argv.index(h) != 1:
TypeError: argument of type 'NoneType' is not iterable

**Comment by justinrporter** [comment]
This doesn't appear to be an error with setup.py at all. Please file a new issue under a more pertinent title. Also, include the command line you ran to get the error (the second-to-last line of the error identifies the command line arguments as being an issue; although I'll agree the error isn't terribly helpful).
