### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

### ISSUE THREAD

**Issue by sbhakat** [bowman-lab/enspara#206]
I was following the enspara tutorial and during plotting of transition probabilities using the following scripts I have encountered the aforementioned error
```
plt.imshow(np.log(m.tprobs_.toarray()))
plt.xticks(range(0, m.n_states_+1))
plt.yticks(range(0, m.n_states_+1))
plt.colorbar(label=r'ln $P(i \rightarrow j)$')
```

It seems like m.tprobs_. doesn't have any attribute` toarray()` I was wondering how to solve this I tried with `plt.imshow(np.log(m.tprobs_.transpose()))` . Is that a correct way to visualize transition between states? Also seems like the plot shown here (https://enspara.readthedocs.io/en/latest/tutorial/fitting.html) is only looking informative if we have 20 states. Any trick to make a nicer plot with more number of states?

**Comment by justinrporter** [comment]
What type is `m.tprobs_`? Most likely it's already an `ndarray`, in which case you can probably just do `plt.imshow(np.log(m.tprobs_.toarray()))`.

> Any trick to make a nicer plot with more number of states?

Generally, if you have tons and tons of states, we don't try to directly visualize our state probabilities. It's just too much. That plot is in the tutorial more to explain the API than to be scientifically useful.

Things I have tried in the past are using [gephi](https://gephi.org/) to import a csv of the transition probabilities and then visualizing things as a directed graph (this works okay) or doing coarse graining (we implement BACE in enspara, [pyemma](http://www.emma-project.org/) has an implementation of tICA) to make it fewer states.

**Comment by sbhakat** [comment]
Hm. Well `m.tprobs_` is an `numpy.ndarray` bit still `m.tprobs_.toarray()` is not an attribute

**Comment by justinrporter** [comment]
Sorry let me clarify: `toarray()` is a property of the [sparse arrays](https://docs.scipy.org/doc/scipy/reference/sparse.html) which are produced by some of the transition matrix builders. Others produce a `ndarray` which don't have a `toarray()` method (the `toarray` method converts a sparse array to an ndarray).

So you should be able to just use `tprobs_` as is without calling toarray (i.e. `plt.imshow(np.log(m.tprobs_))`)!

**Comment by sbhakat** [comment]
Aha, solved. Thanks @justinrporter
