### ISSUE TITLE
Enspara problems with Ragged Array flattening 

### ISSUE THREAD

**Issue by matthew-cruz** [bowman-lab/enspara#217]
Cross posting just in case its at the wrong repo https://github.com/bowman-lab/MSM-docking/issues/17#issue-1492276426

**Comment by justinrporter** [comment]
Link seems to be dead?

**Comment by lgsmith** [comment]
Matt closed the issue because the error was caused by the ragged array
being empty for reasons unrelated to enspara.

**Comment by Justin-J-Miller** [comment]
Closing as this is resolved.
